channels:
- conda-forge
dependencies:
- python=3.10.16
- pip<=24.2
- pip:
  - mlflow==2.20.0
  - cffi==1.17.1
  - cloudpickle==3.1.1
  - colorama==0.4.6
  - jaraco-collections==5.1.0
  - jinja2==3.1.5
  - matplotlib==3.10.0
  - numpy==1.26.4
  - pandas==2.2.3
  - platformdirs==3.11.0
  - pyarrow==11.0.0
  - scikit-learn==1.4.2
  - scipy==1.15.0
  - tpot==1.0.0
name: mlflow-env
